version: "3"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8mb4 --explicit_defaults_for_timestamp=true

  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec foreman start -f Procfile"
    volumes:
      - ./task_management:/task_management
    ports:
      - "3000:3000"
    links:
      - db
