version: 2.1

jobs:
  build:
    machine:
      image: circleci/classic:edge
    working_directory: ~/Glenfiddich
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.20.0-rc2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: docker-compose build
          command: |
            set -x
            docker-compose build
      - run:
          name: docker-compose stop
          command: |
            set -x
            docker-compose stop
      - run:
          name: docker-compose up
          command: |
            set -x
            docker-compose up -d
      - run:
          name: bundle install
          command: |
            set -x
            docker-compose run web bundle install --path=vendor/bundle
      - run:
          name: setup-database
          command: |
            set -x
            docker-compose run web bundle exec rails db:setup RAILS_ENV=test
            docker-compose run web bundle exec rails db:migrate RAILS_ENV=test
      - run:
          name: test
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob 'spec/**/*_spec.rb' | circleci tests split --split-by=timings)"
            docker-compose run web bundle exec rspec --format progress \
                                                                  --format RspecJunitFormatter \
                                                                  --out /tmp/test-results/rspec.xml \
                                                                  $TEST_FILES
      - run:
          name: docker-compose down
          command: docker-compose down
          MYSQL_DATABASE: root
